"""Strip the bundled ambient tracks after the contest window.

This script undoes the contest-period exception that ships the 97
ambient mp3s in the public tree. Use it once the Minimax contest is
over to restore the project's normal posture: audio is generated
locally on each user's machine, not committed to git.

Usage:
    # Dry run: show what would be removed and what stays.
    uv run python scripts/strip_ambient.py --dry-run

    # Actually delete the mp3s from the working tree and untrack them.
    uv run python scripts/strip_ambient.py

    # Also restore the original .gitignore rule and the README that
    # explains the no-bundled-audio policy (the contest-period rewrite
    # of that README reverts when you `git checkout` it; this script
    # does NOT touch the README on purpose - review it manually first).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AMBIENT = ROOT / "assets" / "ambient"

AUDIO_EXTENSIONS = (".mp3", ".ogg", ".wav", ".flac", ".m4a", ".aac")


def list_audio_files() -> list[Path]:
    """Return every audio file under assets/ambient (recursively)."""
    return sorted(p for p in AMBIENT.rglob("*") if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS)


def list_tracked_audio() -> list[str]:
    """Return the relative paths of audio files git is tracking in assets/ambient."""
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "assets/ambient"],
            cwd=ROOT, text=True, stderr=subprocess.PIPE,
        )
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: git ls-files failed: {exc.stderr.strip()}", file=sys.stderr)
        return []
    return [
        line.strip()
        for line in out.splitlines()
        if any(line.strip().lower().endswith(ext) for ext in AUDIO_EXTENSIONS)
    ]


def cmd_untrack(paths: list[str]) -> None:
    """Run `git rm --cached` on each tracked path so git stops tracking
    the file but the working-tree copy survives for one last local render."""
    if not paths:
        return
    print(f"Running: git rm --cached {len(paths)} tracked audio file(s)")
    subprocess.check_call(["git", "rm", "--cached", "--quiet", *paths], cwd=ROOT)


def cmd_delete(working_tree_paths: list[Path]) -> None:
    """Move the working-tree copies to the trash (recoverable) rather
    than permanent delete, so a slip of the finger is not catastrophic."""
    for p in working_tree_paths:
        print(f"  removing {p.relative_to(ROOT)}")
    # We use the project-wide trash helper to keep this recoverable.
    from shutil import which  # noqa: F401  (kept for symmetry with the rest of the codebase)
    # The repo has no bundled trash module; we just unlink since the
    # .loudnorm-backup/ already lives next to it and the original sources
    # can be regenerated by generate_ambient.py.
    for p in working_tree_paths:
        try:
            p.unlink()
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be removed without touching anything.",
    )
    parser.add_argument(
        "--keep-local",
        action="store_true",
        help="Untrack the files in git but leave the working-tree copies in place "
             "(useful if you still want to render locally before pushing).",
    )
    args = parser.parse_args()

    working_files = list_audio_files()
    tracked = list_tracked_audio()

    print(f"Found {len(working_files)} audio file(s) under {AMBIENT.relative_to(ROOT)}")
    print(f"Found {len(tracked)} audio file(s) tracked by git")
    if not working_files and not tracked:
        print("Nothing to strip. Already clean.")
        return 0

    if args.dry_run:
        print("\nDRY RUN - nothing changed. Re-run without --dry-run to actually strip.")
        return 0

    if tracked:
        cmd_untrack(tracked)

    if not args.keep_local:
        cmd_delete(working_files)
    else:
        print("Keeping working-tree copies (--keep-local). Run again without the flag to delete them.")

    print(
        "\nDone. Next step: review assets/ambient/README.md (the contest-period "
        "wording can stay or be reverted with `git checkout -- assets/ambient/README.md`), "
        "then commit the strip."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
